[keyboard]
name = "split keyboard"
product_name = "V1"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "40%ish"
chip = "rp2040"

[layout]
rows = 4
cols = 10
layers = 2
keymap = [
    [
        ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
        ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
        ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
        ["_", "_", "R", "S", "T", "R", "S", "T", "_", "_"],
    ],
]

[light]

[storage]

[split]
connection = "serial"

[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0
serial = [
    { instance = "PIO0", tx_pin = "PIN_12", rx_pin = "PIN_13" }
]

[split.central.matrix]
matrix_type = "direct_pin"
direct_pins = [
    ["PIN_28", "PIN_29", "PIN_0", "PIN_1", "PIN_2"],
    ["PIN_26", "PIN_27", "PIN_3", "PIN_4", "PIN_5"],
    ["PIN_15", "PIN_14", "PIN_6", "PIN_7", "PIN_8"],
    ["_", "_", "PIN_11", "PIN_10", "PIN_9"],
]

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 5
serial = [
    { instance = "PIO0", tx_pin = "PIN_13", rx_pin = "PIN_12" }]

[split.peripheral.matrix]
matrix_type = "direct_pin"
direct_pins = [
    ["PIN_2", "PIN_1", "PIN_0", "PIN_29", "PIN_28"],
    ["PIN_5", "PIN_4", "PIN_3", "PIN_27", "PIN_26"],
    ["PIN_8", "PIN_7", "PIN_6", "PIN_14", "PIN_15"],
    ["PIN_9", "PIN_10", "PIN_11", "_", "_"],
]
