[keyboard]
name = "RMK Keyboard"
product_name = "RMK Keyboard"
vendor_id = 0x4c4b
product_id = 0x4643
chip = "rp2040"

[matrix]
matrix_type = "direct_pin"
direct_pin_low_active = true
direct_pins = [
    ["PIN_1", "PIN_2", "PIN_3", "PIN_4", "PIN_5"],
    ["PIN_6", "PIN_7", "PIN_8", "PIN_9", "PIN_10"],
    ["PIN_11", "PIN_12", "PIN_13", "PIN_14", "PIN_15"],
    ["PIN_16", "PIN_17", "PIN_18", "PIN_19", "PIN_20"],
]

[layout]
rows = 4
cols = 5
layers = 1
keymap = [
    [
        ["A", "B", "C", "D", "E"],
        ["F", "G", "H", "I", "J"],
        ["K", "L", "M", "N", "O"],
        ["P", "Q", "R", "S", "T"],
    ],

]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true



[storage]
# Storage feature is enabled by default
# enabled = false
